### ISSUE TITLE
System.InvalidOperationException in RedisCacheHandle

### ISSUE THREAD

**Issue by rhrasna** [MichaCo/CacheManager#140]
We are often getting connection failed exception on the redis cache handle when the redis serves goes down. We handle it already in our code, but are afraid, whether a new connection is established later. Could you please look at it?
Stacktrace:

	CQRS Queries Api Error Unhandled exception occured in controller System.InvalidOperationException: Failed to initialize instance of type CacheManager.Redis.RedisCacheHandle`1[System.Object]. ---> System.InvalidOperationException: Connection failed.
	   at CacheManager.Redis.RedisConnectionManager.Connect()
	   at CacheManager.Redis.RedisConnectionManager.<get_Servers>d__9.MoveNext()
	   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
	   at CacheManager.Redis.RedisConnectionManager.get_Features()
	   at CacheManager.Redis.RedisCacheHandle`1..ctor(CacheManagerConfiguration managerConfiguration, CacheHandleConfiguration configuration, ILoggerFactory loggerFactory, ICacheSerializer serializer)
	   --- End of inner exception stack trace ---
	   at CacheManager.Core.Internal.CacheReflectionHelper.CreateInstance(Type instanceType, Object[] knownInstances)
	   at CacheManager.Core.Internal.CacheReflectionHelper.CreateCacheHandles[TCacheValue](BaseCacheManager`1 manager, ILoggerFactory loggerFactory, ICacheSerializer serializer)
	   at CacheManager.Core.BaseCacheManager`1..ctor(String name, CacheManagerConfiguration configuration)
	   at CacheManager.Core.BaseCacheManager`1..ctor(CacheManagerConfiguration configuration)
	   at CacheManager.Core.CacheFactory.Build[TCacheValue](String cacheName, Action`1 settings)
	   at CacheManager.Core.CacheFactory.Build(Action`1 settings)
	   at QicsUnity.Infrastructure.Common.Caching.AzureCacheStorage.<>c.<GetNewLazyCacheManagerInitializer>b__13_0()
	   at System.Lazy`1.CreateValue()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Lazy`1.get_Value()
	   at QicsUnity.Infrastructure.Common.Caching.AzureCacheStorage.get_CacheManagerInstance()
	   at QicsUnity.Infrastructure.Common.Caching.AzureCacheStorage.GetObject[TObject](String key, Func`1 loader)
	   at QicsUnity.Common.BusinessObjects.BusinessObjectFactory.CreateUserContext(IUserContextInitializer userContextInitializerOverride)
	   at QicsUnity.Common.Utilities.LogFactory.CreateLogger()

**Comment by MichaCo** [comment]
Well, CacheManager tries to create a connection if there is no client connection present for the given configuration.
So, if you have only one redis configuration (connection string) configured, there will be only one ConnectionMultiplexer open, ever.

If there is no connection established CacheManager tries to connect the moment the instance gets initialized (through injection or new).

Are you treating the CacheManager instance as singleton at all? Just guessing here but it comes from CreateLogger => CreateUserContext, that doesn't sound like it is an app wide singleton instance.

Anyways, since 0.9.3 you can pass in an already connected Redis ConnectionMultiplexer instead of having CacheManager trying to connect. If you want to handle redis connections yourself, just pass one in during configuration.

Apart from that, your exception is clearly connection related, I cannot really do much in that regards.
You could configure connection retries now though with the latest version of StackExchange.Redis.
