### ISSUE TITLE
How to configuration for AWS Elasticache - Redis 

### ISSUE THREAD

**Issue by robvanpamel** [MichaCo/CacheManager#214]
Hi 

Is it possible to connect to an AWS Elasticache Redis instance ? If so how to do this ?

I added my connection string but i'm still getting an exception as mentioned below. 

    Connection to 'cache-server.xxxxx.0001.use1.cache.amazonaws.com:6379,allowAdmin=False,connectTimeout=5000,ssl=False,abortConnect=False,connectRetry=10,proxy=None' failed.: InvalidOperationException
       at CacheManager.Core.BaseCacheManager`1..ctor(String name, ICacheManagerConfiguration configuration)
       at CacheManager.Core.BaseCacheManager`1..ctor(ICacheManagerConfiguration configuration)
       at CacheManager.Core.CacheFactory.Build[TCacheValue](String cacheName, Action`1 settings)

Can you guide me through this ? It is already working on my local machine.

**Comment by robvanpamel** [comment]
the issue was related to AWS VPC. Can be closed
